apiVersion: v1
kind: Service
metadata:
  name: dvsaidevopsb1
  namespace: dvsaidevopsb1-sit
  labels:
    app: myapp
    costcenter: dvsaidevops
spec:
  type: ClusterIP
  selector:
    app: dvsaidevopsb1
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
