trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dvsappacr-conn'
    repository: 'dvsapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    addPipelineData: false
    addBaseImageData: false
