trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
   - group: java-vars


steps:
- task: Bash@3
  displayName: "Code Build"
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      mvn clean package
      ls -l ./target/*.jar
- task: Bash@3
  displayName: "code quality check"
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      export SONAR_TOKEN=$(SONAR_TOKEN)
      mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
      -Dsonar.projectKey=shaanmcdaib1_javaspringbootapp \
      -Dsonar.organization=shaanmcdaib1 \
      -Dsonar.host.url=https://sonarcloud.io \
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'

