apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvsmcdaidemo
  namespace: dvsmcdaidemo-dev
  labels:
    app: dvsmcdaidemo
    costcenter: dvsaidevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dvsmcdaidemo
  template:
    metadata:
      labels:
        app: dvsmcdaidemo
    spec:
      containers:
      - name: dvsmcdaidemo
        image: shan5a6/dvsmcdaidemo:v1.0.0
        ports:
        - containerPort: 8080
---
