apiVersion: v1
kind: Service
metadata:
  name: dvsaidevopsnov
  namespace: dvsaidevopsnov-dev
  labels:
    app: myapp
    costcenter: dvsaidevops
spec:
  type: ClusterIP
  selector:
    app: dvsaidevopsnov
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
